name: verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-library:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install Online Judge Tools
      run: |
        pip install online-judge-tools
        pip install online-judge-verify-helper

    - name: Force sync with remote gh-pages branch
      run: |
        git fetch origin gh-pages
        git reset --hard origin/gh-pages

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all