name: verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-library:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Replace with the desired Python version

    - name: Install Online Judge Tools
      run: |
        pip install online-judge-tools
        pip install online-judge-verify-helper

    - name: Run oj-verify
      run: |
        oj-verify all
